name: Build
permissions:
  contents: read

on:
  push:
    paths:
      - 'src/**'
      - 'thirdparty/**'
  pull_request:
    branches:
      - master
      - main
      - work
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
      fail-fast: false
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Install Odin
      uses: laytan/setup-odin@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release: dev-2026-07

    - name: Install Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.12.2'    

    - name: Build ImGui
      run: cd thirdparty/imgui && python build.py

    - name: Build Box2D
      run: sh $(odin root)/vendor/box2d/build_box2d.sh

    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev

    - name: Run Script
      run: |
        ./build.sh b rel
        mv bin/release/bs_odin/bs_odin bs_odin


    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: bs_odin_${{ matrix.os }}
        path: | 
          bs_odin
          res/
