name: Build
permissions:
  contents: read

on:
  push:
    paths:
      - 'src/**'
      - 'thirdparty/**'
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
      fail-fast: false
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Odin
      uses: laytan/setup-odin@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release: dev-2026-05

    - name: Install Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.12.3'    

    - name: Build Box2D
      run: cd thirdparty/imgui && python build.py

    - name: Build Box2D
      run: sh $(odin root)/vendor/box2d/build_box2d.sh

    - name: Run Script
      run: |
        ./build.sh
